apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          default_type text/plain;
          return 200 "${PASSWORD}\n";
        }
      }
    }
